HOST = "localhost"
PORT = 1945

SHM_NAME = "ppc_project_shm"
SEM_KEY = 6742
MQ_KEY = 11111

MAX_PREY = 100
MAX_PREDATOR = 100

# [0] : Quantité d'herbe
# [1 à 200] : Proies (Par paires : [PID, ETAT])
# [201 à 400] : Prédateurs (Par paires : [PID, ETAT])
IDX_HERBE = 0
IDX_PREY_START = 1
IDX_PREDATOR_START = 1 + (MAX_PREY * 2)

ETAT_MORT = 0
ETAT_ACTIF = 1
ETAT_PASSIF = 2

DEFAULT_H_PREY = 10
DEFAULT_R_PREY = 15
DEFAULT_H_PREDATOR = 30
DEFAULT_R_PREDATOR = 50

INITIAL_ENERGY = 10
COUT_VIE = 1
GAIN_NOURRITURE = 5
COUT_REPRODUCTION = 5

VITESSE_SIMU = 0.5